
x-common-variables: &common-variables
  POSTGRES_DB: genai
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: admin

services:
  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb
    volumes:
      - ./chromadb:/chroma/chroma
    environment:
      # in case you want to persist the data set this to TRUE, and uncomment the volume above
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
      - ANONYMIZED_TELEMETRY=${ANONYMIZED_TELEMETRY:-FALSE}
    ports:
      - "5434:5432"