# x-common-variables: &common-variables

services:
  # nginx:
  #   image: nginx:latest
  #   container_name: diplomovka-reverse-proxy
  #   ports:
  #     - 80:80
  #     - 8080:8080
  #     - 8081:8081
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - chromadb
  #     - smart_home
  #     - agent

  agent:
    image: diplomovka/agent:latest
    build:
      context: src
      dockerfile: Dockerfile
    container_name: diplomovka-agent
    depends_on:
      - chromadb
      - smart_home
    env_file:
      - .env
    environment:
      - CHROMA_HOST=chromadb
      - CHROMA_PORT=8000
      - CHROMA_COLLECTION_NAME=tools
      - EMBEDDING_MODEL=text-embedding-3-small
    volumes:
      - ./src:/src
    ports:
      - "80:80"
    # expose:
      # - "80"

  smart_home:
    build: ./scenarios/smart_home/
    image: smart-home-api:latest
    container_name: smart-home-api
    ports:
      - "8081:80"
    # expose:
      # - "80"

  shopping_history:
    build: ./scenarios/shopping_history/
    image: shopping-history-api:latest
    container_name: shopping-history-api
    ports:
      - "8082:80"
    # expose:
      # - "80"

  inventory_management:
    build: ./scenarios/inventory_management/
    image: inventory-management-api:latest
    container_name: inventory-management-api
    ports:
      - "8083:80"
    # expose:
      # - "80"

  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb
    volumes:
      - ./chromadb/chroma-data:/data
      - ./chromadb/config.yaml:/config.yaml
    # ports:
    #   - "8051:8000"
    expose:
      - "8000"